name: progress_indicator_m3e
description: "Material 3 Expressive progress indicators."
version: 0.1.0
repository: https://github.com/EmilyMoonstone/material_3_expressive/tree/main/packages/progress_indicator_m3e
issue_tracker: https://github.com/EmilyMonestone/material_3_expressive/issues

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  m3e_design: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
