name: progress_indicator_m3e
description: "Material 3 Expressive progress indicators."
version: 0.3.0
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  m3e_design:
    path: ../m3e_design

dev_dependencies:
  flutter_test:
    sdk: flutter
