linter:
  rules:
    always_declare_return_types: true
    directives_ordering: true
    prefer_single_quotes: true
    sort_pub_dependencies: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
