name: fab_m3e
description: Material 3 Expressive Floating Action Button (FAB), Extended FAB, and FAB Menu for Flutter using M3E tokens.
version: 0.1.0
repository: https://github.com/EmilyMoonstone/material_3_expressive/tree/main/packages/fab_m3e
issue_tracker: https://github.com/EmilyMonestone/material_3_expressive/issues

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  m3e_design: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
