name: loading_indicator_m3e
description: Material 3 Expressive Loading Indicator (morphing polygons) for Flutter, with Default and Contained variants.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  m3e_design:
    path: ../m3e_design
  material_new_shapes: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
