name: m3e_gallery
description: Gallery app for Material 3 Expressive packages.
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  m3e_collection:
    path: ../../packages/m3e_collection
  material_color_utilities: ^0.11.0

flutter:
  uses-material-design: true
