name: split_button_m3e
description: "Material 3 Expressive Split Button with sizes, variants, shapes, a11y, and menu."
version: 0.1.0
repository: https://github.com/EmilyMonestone/split_button_m3e
issue_tracker: https://github.com/EmilyMonestone/split_button_m3e/issues

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  m3e_design:
    path: ../m3e_design

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true